site_name: 南方科技大学 科学计算入门
site_description: 南方科技大学 科学计算入门课程 讲义网页
site_author: CRA@SUSTech & CCSE@SUSTech
site_url: https://mirrors.sustech.edu.cn/site/introduction-to-scientific-computation
repo_name: SUSTech-CRA/introduction-to-scientific-computation
repo_url: https://github.com/SUSTech-CRA/introduction-to-scientific-computation
copyright: Brought to you by <a href="https://lug.ustc.edu.cn/">LUG@USTC</a> and <a href="https://blog.sustcra.com/">CRA@SUSTech</a>. Available freely under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 license</a>.

theme:
  name: 'material'
  language: 'zh'
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - attr_list
  - toc:
      permalink: true

extra:
  social:
    - icon: octicons/globe-16
      link: https://blog.sustcra.com/

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js'
  # 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/js/all.min.js'

extra_css:
  - 'css/extra.css'

google_analytics:
  - 'UA-160637954-1'
  - 'auto'

plugins:
  - search


nav:
    - 零：欢迎:
        - 欢迎: index.md
        - 记号约定: notations.md
        - 功劳簿: credits.md
    - 一：初识 Linux:
        - Linux 基本介绍: Ch01/intro.md
        - 桌面环境、终端、SSH 与文件传输: Ch01/desktop-terminal-and-file-transfer.md
        - 进程: Ch01/process.md
        - 编译与安装软件: Ch01/compile-and-install.md
        - 脚本与配置文件的编写与修改: Ch01/script-and-configuration.md
        - 网上冲浪与建站: Ch01/interaction-with-internet.md
        - 拓展阅读: Ch01/supplement.md
        - 思考题解答: Ch01/solution.md
    - 附录:
        - 词汇表: Appendix/glossary.md
        - man 文档的一些示例: Appendix/man.md
        - 其他的 Linux 发行版：技术差异简介: Appendix/distribution.md
